BaseUrl= "http://myblog.com/"
LanguageCode= "en-US"
Title= "My blog"
paginate = 5
DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2016"
canonifyurls = true
theme="casper"



[params]
  description = "this is my description"
  cover = "images/a.jpg"
  author = "charizard42"
  authorlocation = "india"
  authorwebsite = "http://charizard42.in"
  logo = ""
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://www.aweber.com/blog/feed/" 
  githubName = "charizard42"
  twitterName = "charizard42"
  facebookName = "charizard42"
  hideHUGOSupport = false
